name: continuous_integration_build
on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]
jobs:
  continuous_integration_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: continuous_integration_build_make
      run: mkdir -p objects library && make

